# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{state_machine-mongoid}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcin Ciunelis"]
  s.date = %q{2010-06-27}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{marcin.ciunelis@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/state_machine-mongoid.rb",
     "test/helper.rb",
     "test/test_state_machine-mongoid.rb"
  ]
  s.homepage = %q{http://github.com/martinciu/state_machine-mongoid}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{state_machine mongoid integration}
  s.test_files = [
    "test/helper.rb",
     "test/test_state_machine-mongoid.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, [">= 2.0.0.beta7"])
      s.add_runtime_dependency(%q<state_machine>, [">= 0.9.2"])
      s.add_runtime_dependency(%q<activemodel>, [">= 3.0.0.beta4"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
    else
      s.add_dependency(%q<mongoid>, [">= 2.0.0.beta7"])
      s.add_dependency(%q<state_machine>, [">= 0.9.2"])
      s.add_dependency(%q<activemodel>, [">= 3.0.0.beta4"])
      s.add_dependency(%q<test-unit>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid>, [">= 2.0.0.beta7"])
    s.add_dependency(%q<state_machine>, [">= 0.9.2"])
    s.add_dependency(%q<activemodel>, [">= 3.0.0.beta4"])
    s.add_dependency(%q<test-unit>, [">= 0"])
  end
end

